name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJs
      uses: actions/setup-node@v1
      with:
        version: 13.8.0
    - name: Install dependencies
      run: yarn install
